-- MySQL Script generated by MySQL Workbench
-- 07/24/16 02:37:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nim
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nim` ;

-- -----------------------------------------------------
-- Schema nim
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nim` DEFAULT CHARACTER SET utf8 ;
USE `nim` ;

-- -----------------------------------------------------
-- Table `nim`.`nim_trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nim`.`nim_trabajadores` ;

CREATE TABLE IF NOT EXISTS `nim`.`nim_trabajadores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  `experiencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nim`.`nim_oficios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nim`.`nim_oficios` ;

CREATE TABLE IF NOT EXISTS `nim`.`nim_oficios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `oficio` VARCHAR(45) NOT NULL,
  `nim_trabajadores_id` INT NOT NULL,
  PRIMARY KEY (`id`, `nim_trabajadores_id`),
  INDEX `fk_nim_oficios_nim_trabajadores1_idx` (`nim_trabajadores_id` ASC),
  CONSTRAINT `fk_nim_oficios_nim_trabajadores1`
    FOREIGN KEY (`nim_trabajadores_id`)
    REFERENCES `nim`.`nim_trabajadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nim`.`nim_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nim`.`nim_clientes` ;

CREATE TABLE IF NOT EXISTS `nim`.`nim_clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `documento` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nim`.`nim_trabajos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nim`.`nim_trabajos` ;

CREATE TABLE IF NOT EXISTS `nim`.`nim_trabajos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nim_clientes_id` INT NOT NULL,
  `titulo` TEXT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_publicacion` VARCHAR(45) NOT NULL,
  `fecha_expiracion` VARCHAR(45) NOT NULL,
  `status` SMALLINT NOT NULL,
  INDEX `fk_nim_trabajos_nim_clientes1_idx` (`nim_clientes_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_nim_trabajos_nim_clientes1`
    FOREIGN KEY (`nim_clientes_id`)
    REFERENCES `nim`.`nim_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nim`.`nim_trabajador_trabajos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nim`.`nim_trabajador_trabajos` ;

CREATE TABLE IF NOT EXISTS `nim`.`nim_trabajador_trabajos` (
  `nim_trabajadores_id` INT NOT NULL,
  `nim_trabajos_id` INT NOT NULL,
  `comentario` TEXT NOT NULL,
  `calificacion` INT NOT NULL,
  PRIMARY KEY (`nim_trabajos_id`),
  INDEX `fk_nim_trabajador_trabajos_nim_trabajadores1_idx` (`nim_trabajadores_id` ASC),
  INDEX `fk_nim_trabajador_trabajos_nim_trabajos1_idx` (`nim_trabajos_id` ASC),
  CONSTRAINT `fk_nim_trabajador_trabajos_nim_trabajadores1`
    FOREIGN KEY (`nim_trabajadores_id`)
    REFERENCES `nim`.`nim_trabajadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nim_trabajador_trabajos_nim_trabajos1`
    FOREIGN KEY (`nim_trabajos_id`)
    REFERENCES `nim`.`nim_trabajos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
